name: Deploy

on:
  push:
    branches:
      - develop

env:
  NODE_ENV: production
  GH_PAGES_URL: 'https://3594t-deck.github.io'
  GOOGLE_TAG_MANAGER_CONTAINER_ID: ${{secrets.GOOGLE_TAG_MANAGER_CONTAINER_ID}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm --production=false install

      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run deploy
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: GitHub Actions
